# Generated by Django 4.2.1 on 2023-07-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_uploaddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='FileType',
            new_name='type',
        ),
    ]
